### ISSUE TITLE
能否支持 commonjs

### ISSUE THREAD

**Issue by hubingkang** [ishiko732/ts-fsrs#62]

**Comment by ishiko732** [comment]
https://github.com/ishiko732/ts-fsrs/blob/8a669a4d66f5b58a8c7f251d01e627adea9e2221/package.json#L5
通过rollup编译以后是有common.js,如果在common.js环境下显示找不到的话我这边再排查一下

**Comment by hubingkang** [comment]
嗯，我在 nest.js 中无法直接引入使用。

**Comment by ishiko732** [comment]
今天有点晚了，明天再看看修复

**Comment by ishiko732** [comment]
已发布新版本：`ts-fsrs@3.2.3`，麻烦在nest.js试一下咯。
目前next.js 能够正常运行：https://ts-fsrs-demo.vercel.app/

**Comment by ishiko732** [comment]
你好，我在nest.js进行了测试，能够正常使用ts-fsrs了 @hubingkang 
- https://codesandbox.io/p/devbox/nestjs-forked-tjh4w7

**Comment by hubingkang** [comment]
嗯，最新版本已经正常run了
